# Generated by Django 5.2.4 on 2025-08-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_edited_messagehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagehistory',
            old_name='editor',
            new_name='edited_by',
        ),
    ]
